boards:
  - build-target: hellen72
    folder: config/boards/hellen/hellen72
    ini-file: rusefi_hellen72.ini
    skip-rate: 90

  - build-target: hellen81
    folder: config/boards/hellen/hellen81
    ini-file: rusefi_hellen81.ini
    skip-rate: 90

  - build-target: alphax-2chan
    folder: config/boards/hellen/alphax-2chan
    ini-file: rusefi_alphax-2chan.ini
    skip-rate: 0

  - build-target: alphax-4chan
    folder: config/boards/hellen/alphax-4chan
    ini-file: rusefi_alphax-4chan.ini

  - build-target: alphax-4chan_f7
    folder: config/boards/hellen/alphax-4chan
    ini-file: rusefi_alphax-4chan_f7.ini

  - build-target: alphax-8chan
    folder: config/boards/hellen/alphax-8chan
    ini-file: rusefi_alphax-8chan.ini
    skip-rate: 0

  - build-target: alphax-8chan_f7
    folder: config/boards/hellen/alphax-8chan
    ini-file: rusefi_alphax-8chan_f7.ini
    skip-rate: 0

  - build-target: s105
    folder: config/boards/s105
    ini-file: rusefi_s105.ini
    skip-rate: 90

  - build-target: t-b-g
    folder: config/boards/test-build-guards
    ini-file: rusefi_t-b-g.ini
    skip-rate: 90

  - build-target: m74_9
    folder: config/boards/m74_9
    ini-file: rusefi_m74_9.ini
    skip-rate: 80

  - build-target: harley81
    folder: config/boards/hellen/harley81
    ini-file: rusefi_harley81.ini
    skip-rate: 99

  - build-target: small-can-board
    folder: config/boards/hellen/small-can-board
    ini-file: rusefi_small-can-board.ini
    skip-rate: 99

  - build-target: hellen88bmw
    folder: config/boards/hellen/hellen88bmw
    ini-file: rusefi_hellen88bmw.ini
    skip-rate: 99

  - build-target: hellen88bmw_avr
    folder: config/boards/hellen/hellen88bmw
    ini-file: rusefi_hellen88bmw.ini
    skip-rate: 99

  - build-target: hellen-nb1
    folder: config/boards/hellen/hellen-nb1
    ini-file: rusefi_hellen-nb1.ini
    skip-rate: 99

  - build-target: hellen-gm-e67
    folder: config/boards/hellen/hellen-gm-e67
    ini-file: rusefi_hellen-gm-e67.ini
    skip-rate: 99

  - build-target: hellenNA8_96
    folder: config/boards/hellen/hellenNA8_96
    ini-file: rusefi_hellenNA8_96.ini
    skip-rate: 99

  - build-target: hellenNA6
    folder: config/boards/hellen/hellen64_miataNA6_94
    ini-file: rusefi_hellenNA6.ini
    skip-rate: 90

  - build-target: hellen128
    folder: config/boards/hellen/hellen128
    ini-file: rusefi_hellen128mercedes.ini
    skip-rate: 50

  - build-target: hellen121vag
    folder: config/boards/hellen/hellen121vag
    ini-file: rusefi_hellen121vag.ini
    skip-rate: 99

  - build-target: hellen121nissan
    folder: config/boards/hellen/hellen121nissan
    ini-file: rusefi_hellen121nissan.ini

  - build-target: hellen-honda-k
    folder: config/boards/hellen/hellen-honda-k
    ini-file: rusefi_hellen-honda-k.ini

  - build-target: hellen154hyundai
    folder: config/boards/hellen/hellen154hyundai
    ini-file: rusefi_hellen154hyundai.ini
    skip-rate: 90

  - build-target: cypress
    folder: config/boards/cypress
    ini-file: rusefi_cypress.ini

  - build-target: frankenso_na6
    folder: config/boards/frankenso
    ini-file: rusefi_frankenso_na6.ini
    skip-rate: 90

  - build-target: kinetis
    folder: config/boards/kinetis
    ini-file: rusefi_kin.ini
    skip-rate: 0

  - build-target: mre_f4
    folder: config/boards/microrusefi
    ini-file: rusefi_mre_f4.ini

  - build-target: mre_f4_no_openblt
    folder: config/boards/microrusefi
    ini-file: rusefi_mre_f4.ini

  - build-target: mre_f4_debug
    folder: config/boards/microrusefi
    ini-file: rusefi_mre_f4.ini
    skip-rate: 80

  - build-target: mre_f4_recovery
    folder: config/boards/microrusefi
    ini-file: rusefi_mre_f4.ini
    skip-rate: 95

  - build-target: mre_f4_hardware_QC_special_build
    folder: config/boards/microrusefi
    ini-file: rusefi_mre_f4.ini
    skip-rate: 90

  - build-target: mre_f7
    folder: config/boards/microrusefi
    ini-file: rusefi_mre_f7.ini
    skip-rate: 90

  - build-target: prometheus_405
    folder: config/boards/prometheus
    ini-file: rusefi_prometheus_405.ini
    skip-rate: 90

  - build-target: prometheus_469
    folder: config/boards/prometheus
    ini-file: rusefi_prometheus_469.ini
    skip-rate: 90

  - build-target: proteus_f4
    folder: config/boards/proteus
    ini-file: rusefi_proteus_f4.ini

  - build-target: proteus_f4_hardware_QC_special_build
    folder: config/boards/proteus
    ini-file: rusefi_proteus_f4.ini

  - build-target: proteus_f7
    folder: config/boards/proteus
    ini-file: rusefi_proteus_f7.ini

  - build-target: proteus_f7_debug
    folder: config/boards/proteus
    ini-file: rusefi_proteus_f7.ini
    skip-rate: 80

  - build-target: proteus_f7_hardware_QC_special_build
    folder: config/boards/proteus
    ini-file: rusefi_proteus_f7.ini
    skip-rate: 0

  - build-target: proteus_h7
    folder: config/boards/proteus
    ini-file: rusefi_proteus_h7.ini
    skip-rate: 90

  - build-target: stm32f429_nucleo
    folder: config/boards/nucleo_f429
    ini-file: rusefi_stm32f429_nucleo.ini

  - build-target: stm32f767_nucleo
    folder: config/boards/nucleo_f767
    ini-file: rusefi_stm32f767_nucleo.ini
    skip-rate: 95

  - build-target: stm32h743_nucleo
    folder: config/boards/nucleo_h743
    ini-file: rusefi_stm32h743_nucleo.ini
    skip-rate: 95

  - build-target: subaru_eg33_f7
    folder: config/boards/subaru_eg33
    ini-file: rusefi_subaru_eg33_f7.ini
    skip-rate: 50

  - build-target: subaru_eg33_f7_no_bl
    folder: config/boards/subaru_eg33
    ini-file: rusefi_subaru_eg33_f7.ini
    skip-rate: 50

  - build-target: f407-discovery
    folder: config/boards/f407-discovery
    ini-file: rusefi_f407-discovery.ini
    skip-rate: 0

  #          - build-target: f407-discovery_debug
  #            folder: config/boards/f407-discovery
  #            ini-file: rusefi_f407-discovery.ini
  #            skip-rate: 0

  - build-target: f429-discovery
    folder: config/boards/f429-discovery
    ini-file: rusefi_f429-discovery.ini
    skip-rate: 95

  - build-target: core8
    folder: config/boards/core8
    ini-file: rusefi_core8.ini
    skip-rate: 95

  - build-target: 48way
    folder: config/boards/48way
    ini-file: rusefi_48way.ini
    skip-rate: 95

  - build-target: atlas
    folder: config/boards/atlas
    ini-file: rusefi_atlas.ini
    skip-rate: 95

  - build-target: tdg-pdm8
    folder: config/boards/tdg-pdm8
    ini-file: rusefi_tdg-pdm8.ini
    skip-rate: 95
